### ISSUE TITLE
虎碼測評網「F」「H」比較低是因爲簡軆的原因嗎？

### ISSUE THREAD

**Issue by ywxt** [orbitoo/kumo#1]
感覺「F」「H」要低很多，相反「V」「B」高了不少。

**Comment by orbitoo** [comment]
> 感覺「F」「H」要低很多，相反「V」「B」高了不少。

是的，我是一箇愛折中的人，旣選擇簡繁具做，則都入攷量。在優化中，繁簡碼表均計算分佈竝優化，因此單看簡化字不足以反映我使用中的眞實分佈；繁簡分離的設計也會使某些鍵於簡化字中罕用。想要在一方面更突出性能應當攷慮別種方案。

**Comment by ywxt** [comment]
感謝回覆，不過感覺大陸的方案應該不太會攷慮爲繁軆做特別的優化。



---Original---
From: ***@***.***&gt;
Sent at: 2023年11月1日(Wed) Evening10:36
To: ***@***.***&gt;;
Cc: "Cui ***@***.******@***.***&gt;;
Subject: Re: [orbitoo/kumo] 虎碼測評網「F」「H」比較低是因爲簡軆的原因嗎？ (Issue #1)




  
感覺「F」「H」要低很多，相反「V」「B」高了不少。
  
是的，我是一箇愛折中的人，卽選擇簡繁具做，則都入攷量。在優化中，繁簡碼表均計算分佈竝優化，因此單看簡化字不足以反映我使用中的眞實分佈；繁簡分離的設計也會使某些鍵於簡化字中罕用。想要在一方面更突出性能應當攷慮別種方案。
